# File: .github/workflows/workflow.yml
name: Run Azure Login With a Service Principal Secret

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO

permissions:
      id-token: write
      contents: read


#on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI k
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # Run Terraform init
    - name: Terraform init
      
      id: init
      run: terraform init  

    - name: Terraform plan
      
      id: plan
      run: terraform plan

    - name: Terraform apply

      id: apply
      run: terraform apply -auto-approve