# File: .github/workflows/workflow.yml
name: Run Azure Login With a Service Principal Secret

on:
  push:
    branches:
      - main

env:
  TF_LOG: INFO

permissions:
      id-token: write
      contents: read


#on: [push]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI kkk
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    
    - uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

      
    - uses: azure/login@v2
      with:
        auth-type: SERVICE_PRINCIPAL
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

    - name: 'Run az commands'
      run: |
        az account show 

    # Run Terraform init
    - name: Terraform init
      
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      run: terraform init  

    - name: Terraform plan
      
      id: plan
      run: terraform plan

    - name: Terraform apply

      id: apply
      run: terraform apply -auto-approve